spring:
  profiles:
    active: dev  # "prod" если продакшен

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

  app:
    pricing:
      scale: 2
      free-threshold: 0.01
      max-discount: 100
      min-price: 0

  jackson:
    serialization:
      write-dates-as-timestamps: false

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    output:
 #     ansi:
 #       enabled: always

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

server:
  error:
    include-message: never
    include-binding-errors: never
    include-exception: false

app:
  security:
    cookie:
      access:
        httpOnly: true
        secure: true
        sameSite: Strict  # только прямые
        maxAgeSeconds: 900       # 15 минут
      refresh:
        httpOnly: true
        secure: true
        sameSite: Lax # можно с других сайтов
        maxAgeSeconds: 2592000   # 30 дней
    jwt:
      access-token-validity-seconds: 900        # 15 минут
      refresh-token-validity-seconds: 2592000   # 30 дней
